{% set name = "parabem" %}
{% set version = "0.2.0" %}
{% set sha256 = "0f9f209b593d84ae3c83dcf961cc5cac06d6db9c0daa601f25106954868fc04d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/booya-at/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - cmake.patch

build:
  number: 2
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('cxx') }}
    - ninja
    - cmake 3.15
  host:
    - python
    - pybind11
    - eigen
    - openmpi      # [linux]
    - llvm-openmp      # [osx]
  run:
    - python
    - numpy
    - matplotlib-base
    - llvm-openmp      # [osx]

test:
  imports:
    - parabem

about:
  home: https://github.com/booya-at/paraBEM
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: potential flow with boundary elements.
  doc_url: https://github.com/booya-at/paraBEM/blob/master/doc/tutorial/tutorial.ipynb
  dev_url: https://github.com/booya-at/paraBEM

extra:
  recipe-maintainers:
    - looooo
