{% set name = "parabem" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/booya-at/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 1d516a010b12def0a67b6f50723bd94c6ae84e376cb2a2744b685576dccf84c6

build:
  number: 0

requirements:
  build:    
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - ninja
    - cmake
  host:
    - python
    - pybind11
    - eigen
    - openmpi      # [linux]
    - llvm-openmp      # [osx]
  run:
    - python
    - numpy
    - matplotlib-base

test:
  imports:
    - parabem

about:
  home: https://github.com/booya-at/paraBEM
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: potential flow with boundary elements.
  doc_url: https://github.com/booya-at/paraBEM/blob/master/doc/tutorial/tutorial.ipynb
  dev_url: https://github.com/booya-at/paraBEM

extra:
  recipe-maintainers:
    - looooo
