{% set name = "parabem" %}
{% set version = "0.3.0" %}
{% set sha256 = "cb2575d50abac694b72324a5ca094d78eaadf4fdfd71eefaadbdc118da9e5fcd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/booya-at/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - ninja
    - cmake
    - pip
    - python
  host:
    - python
    - pybind11
    - eigen
    - openmpi      # [linux]
    - llvm-openmp      # [osx]
  run:
    - python
    - numpy
    - matplotlib-base
    - llvm-openmp      # [osx]

test:
  imports:
    - parabem

about:
  home: https://github.com/booya-at/paraBEM
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: potential flow with boundary elements.
  doc_url: https://github.com/booya-at/paraBEM/blob/master/doc/tutorial/tutorial.ipynb
  dev_url: https://github.com/booya-at/paraBEM

extra:
  recipe-maintainers:
    - looooo
