context:
  name: parabem
  version: "1.0.2"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/booya-at/${{ name }}/archive/${{ version }}.tar.gz
  sha256: cfdd9f2a7b56e0ab2470e5eb9738c818e9417f6f48a715ebc91b0333af1152a8

build:
  number: 0

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ninja
    - cmake
  host:
    - python
    - pybind11
    - eigen
    - if: linux
      then: openmpi
    - if: osx
      then: llvm-openmp
  run:
    - python
    - numpy
    - matplotlib-base

tests:
  - python:
      imports:
        - parabem

about:
  homepage: https://github.com/booya-at/paraBEM
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: potential flow with boundary elements.
  documentation: https://github.com/booya-at/paraBEM/blob/master/doc/tutorial/tutorial.ipynb
  repository: https://github.com/booya-at/paraBEM

extra:
  recipe-maintainers:
    - looooo
