travis:
  secure:
    BINSTAR_TOKEN: sGbVpeZ89bAxVcc0qOlRoQOHgA9P+vODidAtkCKbm+GG0GAweiy+tS/MPVO0aN62YIlmpFO5B2lK0X6BJICkV4da15EvCj4xOG82FllXzKw7fe0/5G3cRYPgdsZK4W8X1SEEo2Qyks4jquufZdpaOIrpTN6AooIl5rpKoj+yz/X/uSpKsCwH80+i4kn4vdwy5va5JjUinhTc1jCr198TPhP53K4iUoVMI6+U7B+Wy49c0TxmmilBBl8XOhLQRu7CWkXJ8Y5tG6ZRkpgfJv8dqRHiJ9kLwB5igtIaTEewO1wyuWm2UI5BrMJo52g3o1jP0REpqIBUVe+D1V8cBEi4IPcug93pvOk12QF/Lv4nQiJHnmWsMWAeu2zQYF9Wr93lDGNFVAJRA3cHhnGi9TVjUGW+Jg5uszBqf9GKIJg7sQuOtpjyFl2jYZFuLoPOuJxxP92nBTbBrHxqf2dZD576jxcmAmr+Pu0quYFJME0dhqJFaiUovvfdHvOjaPUgrJKPp2ge3IR71WDql3zotNSuwRZuIxVCNyPikPHzPUZ/rKXfRHr/Qj79S5VhDT/wn8LfAC4lpPvC9x0J2Yy0CNUB8s6s7kW7zOkuInFEX9so8h4qYHQ1JS2YZ3vCcXrqelOZRWSkUnO/qWoBgqAJaVSICDnNBzVMADYDF8FL+zghpXI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
